file_format: "1"
id: leeloov2
name: Leeloo v2
type: shield
url: https://clicketysplit.ca/pages/leeloo
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - backlight
siblings:
  - leeloov2_left
  - leeloov2_right
