file_format: "1"
id: leeloo
name: Leeloo
type: shield
url: https://clicketysplit.ca/pages/leeloo
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - leeloo_left
  - leeloo_right
